name: gakujo_gui
description: GakujoGUI

publish_to: "none"

version: 1.2.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  sticky_headers: ^0.3.0+2
  package_info_plus: ^3.0.3
  cookie_jar: ^3.0.1
  dio: ^5.1.1
  dio_cookie_manager: ^2.1.3
  encrypted_shared_preferences: ^3.0.1
  html: ^0.15.2
  shared_preferences: ^2.0.15
  wakelock: ^0.6.2
  html_unescape: ^2.0.0
  version: ^3.0.2
  uuid: ^3.0.7
  provider: ^6.0.5
  url_launcher: ^6.1.10
  collection: ^1.17.0
  crypto: ^3.0.2
  flutter_slidable: ^2.0.0
  share_plus: ^6.3.1
  path: ^1.8.2
  better_open_file: ^3.6.4
  path_provider: ^2.0.14
  selectable_autolink_text: ^2.5.0
  flutter_secure_storage: ^8.0.0
  cached_memory_image: ^1.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flash: ^2.0.5+1
  fl_chart: ^0.61.0
  adaptive_dialog: ^1.8.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: 6c66ad2
  line_icons: ^2.0.1
  multi_split_view: ^2.4.0
  side_sheet: ^1.0.4
  windows_taskbar: ^1.1.1
  badges: ^3.0.3
  flutter_speed_dial: ^6.2.0
  google_fonts: ^4.0.3
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/android/play_store_512.png"
  adaptive_icon_background: "assets/images/android/res/mipmap-xxxhdpi/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/images/android/res/mipmap-xxxhdpi/ic_launcher_foreground.png"
  windows:
    generate: true
    image_path: "assets/images/android/play_store_512.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/android/play_store_512.png"

flutter:
  uses-material-design: true
