name: gakujo_task
description: GakujoTask

publish_to: "none"

version: 1.1.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  timeline_tile: ^2.0.0
  intl: ^0.17.0
  sticky_headers: "^0.3.0"
  package_info_plus: ^3.0.2
  cookie_jar: ^3.0.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  encrypted_shared_preferences: ^3.0.1
  html: ^0.15.1
  shared_preferences: ^2.0.15
  wakelock: ^0.6.2
  html_unescape: ^2.0.0
  version: ^3.0.0
  flutter_dotenv: ^5.0.2
  uuid: ^3.0.7
  dio_smart_retry: ^1.3.2
  provider: ^6.0.4
  fluttertoast: ^8.1.1
  url_launcher: ^6.1.7
  collection: ^1.16.0
  crypto: ^3.0.2
  flutter_slidable: ^2.0.0
  share_plus: ^6.3.0
  file_saver: ^0.1.1
  path: ^1.8.2
  better_open_file: ^3.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
