class Syllabus {
  String subject;
  String teacher;
  String affiliation;
  String researchRoom;
  String sharingTeacher;
  String className;
  String semesterName;
  String selectionSection;
  String targetGrade;
  String credit;
  String weekdayPeriod;
  String classRoom;
  String keyword;
  String classTarget;
  String learningDetail;
  String classPlan;
  String classRequirement;
  String textbook;
  String referenceBook;
  String preparationReview;
  String evaluationMethod;
  String officeHour;
  String message;
  String activeLearning;
  String teacherPracticalExperience;
  String teacherCareerClassDetail;
  String teachingProfessionSection;
  String relatedClassSubjects;
  String other;
  String homeClassStyle;
  String homeClassStyleDetail;

  Syllabus({
    required this.subject,
    required this.teacher,
    required this.affiliation,
    required this.researchRoom,
    required this.sharingTeacher,
    required this.className,
    required this.semesterName,
    required this.selectionSection,
    required this.targetGrade,
    required this.credit,
    required this.weekdayPeriod,
    required this.classRoom,
    required this.keyword,
    required this.classTarget,
    required this.learningDetail,
    required this.classPlan,
    required this.classRequirement,
    required this.textbook,
    required this.referenceBook,
    required this.preparationReview,
    required this.evaluationMethod,
    required this.officeHour,
    required this.message,
    required this.activeLearning,
    required this.teacherPracticalExperience,
    required this.teacherCareerClassDetail,
    required this.teachingProfessionSection,
    required this.relatedClassSubjects,
    required this.other,
    required this.homeClassStyle,
    required this.homeClassStyleDetail,
  });
}
